**1.1. Загрузка данных Azure Public Dataset**

Источник: https://github.com/Azure/AzurePublicDataset/tree/master

Датасет: AzurePublicDatasetV2 (2019)

In [3]:
# Скачивание vmtable.csv.gz (метаданные)
!wget -O vmtable.csv.gz "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vmtable/vmtable.csv.gz"

--2026-04-16 19:20:15--  https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vmtable/vmtable.csv.gz
Resolving azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)... 52.239.236.228
Connecting to azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)|52.239.236.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 437594496 (417M) [application/octet-stream]
Saving to: ‘vmtable.csv.gz’

vmtable.csv.gz      100%[===================>] 417.32M  8.94MB/s    in 41s

2026-04-16 19:20:57 (10.1 MB/s) - ‘vmtable.csv.gz’ saved [437594496/437594496]

In [28]:
vmtable = pd.read_csv(
    "vmtable.csv.gz",
    compression="gzip",
    header=None
)

print(vmtable.shape)
vmtable.head()

(2695548, 11)

,0,1,2,3,4,5,6,7,8,9,10
0,71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH...,GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R...,2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr...,558300,1673700,91.776885,0.728879,20.759630,Delay-insensitive,8,32
1,rKggHO/04j31UFy65mDTwtjdMQL/G03xWfl3xGeiilB4/W...,ub4ty8ygwOECrIz7eaZ/9hDwnCsERvZ3nJJ03sDSpD85et...,+ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHFmyJ...,424500,425400,37.879261,3.325358,37.879261,Unknown,4,32
2,YrR8gPtBmfNaOdnNEW5If1SdTqQgGQHEnLHGPjySt53bKW...,9LrdYRcUfGbmL2fFfLR/JUg2OTkjGRe3iluwIhDRPnPDPa...,GEyIElfPSFupze8T+T1niQMepeqG88VpLNuxUMyIDbz8VF...,1133100,1133700,0.304368,0.220553,0.304368,Unknown,4,32
3,xzQ++JF1UAkh70CDhmzkiOo+DQn+E2TLErCFKEmSswv1pl...,0XnZZ8sMN5HY+Yg+0dykYB5oenlgsrCpzpgFSvn/MX42Ze...,7aCQS6fPUw9rwCPiqvghk/WCEbMV3KgNJjA+sssdfY5Ybl...,0,2591400,98.573424,30.340054,98.212503,Interactive,2,4
4,vZEivnhabRmImDr+JqKqZnpIM3WxtypwoxjfjnklR/idyR...,HUGaZ+piPP4eHjycCBki2yq0raJywdzrVuriR6nQceH3hA...,/s/D5VtTQDxyS6wq7N/VQAMczx61Ny1Ut3a3iFmDSOCXxp...,228300,229800,82.581449,13.876299,82.581449,Unknown,2,4

In [29]:
vmtable.columns = [
    "vmid",
    "subscription_id",
    "deployment_id",
    "vm_created",
    "vm_deleted",
    "max_cpu",
    "avg_cpu",
    "p95_max_cpu",
    "vm_category",
    "core_bucket",
    "memory_bucket"
]

In [1]:
# Скачивание первого CPU-файла
!wget -O vm_cpu_readings-file-1-of-195.csv.gz "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vm_cpu_readings/vm_cpu_readings-file-1-of-195.csv.gz"

--2026-04-16 19:04:46--  https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/trace_data/vm_cpu_readings/vm_cpu_readings-file-1-of-195.csv.gz
Resolving azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)... 52.239.236.228
Connecting to azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)|52.239.236.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 856259637 (817M) [application/octet-stream]
Saving to: ‘vm_cpu_readings-file-1-of-195.csv.gz’

vm_cpu_readings-fil 100%[===================>] 816.59M  7.27MB/s    in 80s

2026-04-16 19:06:07 (10.2 MB/s) - ‘vm_cpu_readings-file-1-of-195.csv.gz’ saved [856259637/856259637]

In [19]:
import pandas as pd

cpu1 = pd.read_csv(
    "vm_cpu_readings-file-1-of-195.csv.gz",
    compression="gzip",
    header=None,
    nrows=100000
)

cpu1.head()

,0,1,2,3,4
0,0,yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1Q...,19.898441,24.996361,22.630673
1,0,gVb4X4iS13nJrM0KZsy7SrHzWAHix0CEPlK7/deV5vkwjt...,14.281488,20.028324,17.250655
2,0,f8BtQHczrXFjnVxWl8Hqm1kH9UD/8nCvtXCLiFvVRvamqa...,1.655368,23.138685,8.533818
3,0,8xjtVrJRJAyArNlbRgCftoNQOZiWl2eRP6uQavL9+6IULT...,47.501061,52.940579,50.045584
4,0,zTE3f0H2n43tW+PA3OdonjUTWWxeyzF7xJk9QH9s/487J/...,1.724155,12.889580,4.833578

In [24]:
cpu1.columns = [
    "timestamp",
    "vmid",
    "min_cpu",
    "max_cpu",
    "avg_cpu"
]

In [8]:
# Количество строк во всем CPU-файле
import pandas as pd

row_count = 0

for chunk in pd.read_csv("vm_cpu_readings-file-1-of-195.csv.gz",
                         compression="gzip",
                         chunksize=100000):
    row_count += len(chunk)

print("Всего строк:", row_count)

Всего строк: 9999999

In [31]:
# Скачивание schema.csv
!wget -O schema.csv "https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/schema.csv"

--2026-04-16 20:01:44--  https://azurepublicdatasettraces.blob.core.windows.net/azurepublicdatasetv2/schema.csv
Resolving azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)... 52.239.236.228
Connecting to azurepublicdatasettraces.blob.core.windows.net (azurepublicdatasettraces.blob.core.windows.net)|52.239.236.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1485 (1.5K) [application/vnd.ms-excel]
Saving to: ‘schema.csv’

schema.csv          100%[===================>]   1.45K  --.-KB/s    in 0s

2026-04-16 20:01:44 (538 MB/s) - ‘schema.csv’ saved [1485/1485]

**1.2. Изучение структуры и типов данных**

In [32]:
# Схема данных
import pandas as pd

schema = pd.read_csv("schema.csv")
print("Размер schema:", schema.shape)
display(schema)

Размер schema: (25, 4)

,filepattern,field_number,content,format
0,vm_virtual_core_bucket_definition.csv,1,bucket,STRING
1,vm_virtual_core_bucket_definition.csv,2,definition,STRING
2,vm_memory_bucket_definition.csv,1,bucket,STRING
3,vm_memory_bucket_definition.csv,2,definition,STRING
4,subscriptions/subscriptions.csv.gz,1,subscription id,STRING_HASH
5,subscriptions/subscriptions.csv.gz,2,timestamp first vm created,INTEGER
6,subscriptions/subscriptions.csv.gz,3,count vms created,INTEGER
7,deployment/deployment.csv.gz,1,deployment id,STRING_HASH
8,deployment/deployment.csv.gz,2,deployment size,INTEGER
9,vmtable/vmtable.csv.gz,1,vm id,STRING_HASH
10,vmtable/vmtable.csv.gz,2,subscription id,STRING_HASH
11,vmtable/vmtable.csv.gz,3,deployment id,STRING_HASH
12,vmtable/vmtable.csv.gz,4,timestamp vm created,INTEGER
13,vmtable/vmtable.csv.gz,5,timestamp vm deleted,INTEGER
14,vmtable/vmtable.csv.gz,6,max cpu,DOUBLE
15,vmtable/vmtable.csv.gz,7,avg cpu,DOUBLE
16,vmtable/vmtable.csv.gz,8,p95 max cpu,DOUBLE
17,vmtable/vmtable.csv.gz,9,vm category,STRING
18,vmtable/vmtable.csv.gz,10,vm virtual core count bucket,STRING
19,vmtable/vmtable.csv.gz,11,vm memory (gb) bucket,STTRING
20,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,1,timestamp,INTEGER
21,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,2,vm id,STRING_HASH
22,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,3,min cpu,DOUBLE
23,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,4,max cpu,DOUBLE
24,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,5,avg cpu,DOUBLE

In [11]:
# Схема vmtable
schema_vmtable = schema[schema["filepattern"].str.contains("vmtable", na=False)]
display(schema_vmtable)

,filepattern,field_number,content,format
9,vmtable/vmtable.csv.gz,1,vm id,STRING_HASH
10,vmtable/vmtable.csv.gz,2,subscription id,STRING_HASH
11,vmtable/vmtable.csv.gz,3,deployment id,STRING_HASH
12,vmtable/vmtable.csv.gz,4,timestamp vm created,INTEGER
13,vmtable/vmtable.csv.gz,5,timestamp vm deleted,INTEGER
14,vmtable/vmtable.csv.gz,6,max cpu,DOUBLE
15,vmtable/vmtable.csv.gz,7,avg cpu,DOUBLE
16,vmtable/vmtable.csv.gz,8,p95 max cpu,DOUBLE
17,vmtable/vmtable.csv.gz,9,vm category,STRING
18,vmtable/vmtable.csv.gz,10,vm virtual core count bucket,STRING
19,vmtable/vmtable.csv.gz,11,vm memory (gb) bucket,STTRING

In [12]:
# Схема vm_cpu_readings
schema_cpu = schema[schema["filepattern"].str.contains("vm_cpu_readings", na=False)]
display(schema_cpu)

,filepattern,field_number,content,format
20,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,1,timestamp,INTEGER
21,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,2,vm id,STRING_HASH
22,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,3,min cpu,DOUBLE
23,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,4,max cpu,DOUBLE
24,vm_cpu_readings/vm_cpu_readings-file-*-of-195....,5,avg cpu,DOUBLE

In [13]:
# Структура vmtable
vmtable = pd.read_csv("vmtable.csv.gz", compression="gzip")

print("Размер vmtable:", vmtable.shape)
print("\nКолонки vmtable:")
print(vmtable.columns.tolist())

display(vmtable.head())

Размер vmtable: (2695547, 11)

Колонки vmtable:
['71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB', 'GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR', '2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==', '558300', '1673700', '91.776885421193157', '0.72887880462586729', '20.759629514971522', 'Delay-insensitive', '8', '32']

,71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB,GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR,2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==,558300,1673700,91.776885421193157,0.72887880462586729,20.759629514971522,Delay-insensitive,8,32
0,rKggHO/04j31UFy65mDTwtjdMQL/G03xWfl3xGeiilB4/W...,ub4ty8ygwOECrIz7eaZ/9hDwnCsERvZ3nJJ03sDSpD85et...,+ZraIDUNaWYDZMBiBtZm7xSjr+j3zcHGjup1+wyKxHFmyJ...,424500,425400,37.879261,3.325358,37.879261,Unknown,4,32
1,YrR8gPtBmfNaOdnNEW5If1SdTqQgGQHEnLHGPjySt53bKW...,9LrdYRcUfGbmL2fFfLR/JUg2OTkjGRe3iluwIhDRPnPDPa...,GEyIElfPSFupze8T+T1niQMepeqG88VpLNuxUMyIDbz8VF...,1133100,1133700,0.304368,0.220553,0.304368,Unknown,4,32
2,xzQ++JF1UAkh70CDhmzkiOo+DQn+E2TLErCFKEmSswv1pl...,0XnZZ8sMN5HY+Yg+0dykYB5oenlgsrCpzpgFSvn/MX42Ze...,7aCQS6fPUw9rwCPiqvghk/WCEbMV3KgNJjA+sssdfY5Ybl...,0,2591400,98.573424,30.340054,98.212503,Interactive,2,4
3,vZEivnhabRmImDr+JqKqZnpIM3WxtypwoxjfjnklR/idyR...,HUGaZ+piPP4eHjycCBki2yq0raJywdzrVuriR6nQceH3hA...,/s/D5VtTQDxyS6wq7N/VQAMczx61Ny1Ut3a3iFmDSOCXxp...,228300,229800,82.581449,13.876299,82.581449,Unknown,2,4
4,MqvcZ6Au5ouI6if56MJHmoSqHtX8oRv0dPkaxCId3aUcr1...,p14cXGYqCKCcF7b7OdV6bdr/0gCim+u1LeqKoyEkyNNMWf...,ZFCk80sIQzr43FUSqy2DOrcvBhuQkyfVz7gus8SORhyBxC...,1395600,1397700,0.097875,0.035215,0.097875,Unknown,4,32

In [14]:
# Типы данных и пропуски в vmtable
vmtable.info()

print("\nДоля пропусков в vmtable:")
display(vmtable.isna().mean().sort_values(ascending=False))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2695547 entries, 0 to 2695546
Data columns (total 11 columns):
 #   Column                                                                                    Dtype
---  ------                                                                                    -----
 0   71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB                          object
 1   GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR                          object
 2   2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==  object
 3   558300                                                                                    int64
 4   1673700                                                                                   int64
 5   91.776885421193157                                                                        float64
 6   0.72887880462586729                                                                       float64
 7   20.759629514971522                                                                        float64
 8   Delay-insensitive                                                                         object
 9   8                                                                                         object
 10  32                                                                                        object
dtypes: float64(3), int64(2), object(6)
memory usage: 226.2+ MB

Доля пропусков в vmtable:

71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB                            0.0
GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR                            0.0
2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==    0.0
558300                                                                                      0.0
1673700                                                                                     0.0
91.776885421193157                                                                          0.0
0.72887880462586729                                                                         0.0
20.759629514971522                                                                          0.0
Delay-insensitive                                                                           0.0
8                                                                                           0.0
32                                                                                          0.0
dtype: float64

In [15]:
# Структура CPU-файлов
cpu1 = pd.read_csv(
    "vm_cpu_readings-file-1-of-195.csv.gz",
    compression="gzip"
)

print("Размер cpu1:", cpu1.shape)
print("\nКолонки cpu1:")
print(cpu1.columns.tolist())

display(cpu1.head())

Размер cpu1: (9999999, 5)

Колонки cpu1:
['0', 'yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X', '19.898441030801841', '24.996361191759995', '22.630672687116984']

,0,yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X,19.898441030801841,24.996361191759995,22.630672687116984
0,0,gVb4X4iS13nJrM0KZsy7SrHzWAHix0CEPlK7/deV5vkwjt...,14.281488,20.028324,17.250655
1,0,f8BtQHczrXFjnVxWl8Hqm1kH9UD/8nCvtXCLiFvVRvamqa...,1.655368,23.138685,8.533818
2,0,8xjtVrJRJAyArNlbRgCftoNQOZiWl2eRP6uQavL9+6IULT...,47.501061,52.940579,50.045584
3,0,zTE3f0H2n43tW+PA3OdonjUTWWxeyzF7xJk9QH9s/487J/...,1.724155,12.889580,4.833578
4,0,oJXXVhFJaulRsMKo8iZ7PWewFKPbuwQtyXbR0IjQOWli8G...,11.927168,20.426842,16.279067

In [16]:
# Типы данных и пропуски в cpu1
cpu1.info()

print("\nДоля пропусков в cpu1:")
display(cpu1.isna().mean().sort_values(ascending=False))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999999 entries, 0 to 9999998
Data columns (total 5 columns):
 #   Column                                                            Dtype
---  ------                                                            -----
 0   0                                                                 int64
 1   yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X  object
 2   19.898441030801841                                                float64
 3   24.996361191759995                                                float64
 4   22.630672687116984                                                float64
dtypes: float64(3), int64(1), object(1)
memory usage: 381.5+ MB

Доля пропусков в cpu1:

0                                                                   0.0
yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X    0.0
19.898441030801841                                                  0.0
24.996361191759995                                                  0.0
22.630672687116984                                                  0.0
dtype: float64

In [17]:
print("Колонки vmtable:", vmtable.columns.tolist())
print("Колонки cpu1:", cpu1.columns.tolist())

Колонки vmtable: ['71fJw0x+SDRdAxKPwLyHZhTgQpYw2afS6tjJhfT6kHnmLH54/rl2etJKUpSFKoTB', 'GB6uQC1NSArW5n+TtOybL7GQ1yByjuWtZnsj+5QccZ525R2wi5t9jPe8K5tU8MjR', '2sh/ZjaYdfpslv4iYBfNzFe4rs982kHVvNGJGeQ8MIBCDr3EBYlXlNvViSonMAjfFuCpsbEPDDfydWwf/naB5Q==', '558300', '1673700', '91.776885421193157', '0.72887880462586729', '20.759629514971522', 'Delay-insensitive', '8', '32']
Колонки cpu1: ['0', 'yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1QPfeKR5//6xyX0VYn7X', '19.898441030801841', '24.996361191759995', '22.630672687116984']

In [33]:
#JOIN
merged = cpu1.merge(vmtable, on="vmid", how="left")

print(merged.shape)
merged.head()

(100000, 15)

,timestamp,vmid,min_cpu,max_cpu_x,avg_cpu_x,subscription_id,deployment_id,vm_created,vm_deleted,max_cpu_y,avg_cpu_y,p95_max_cpu,vm_category,core_bucket,memory_bucket
0,0,yNf/R3X8fyXkOJm3ihXQcT0F52a8cDWPPRzTT6QFW8N+1Q...,19.898441,24.996361,22.630673,GStyJfehx9FBLRCvqDxCk4Hpxi8bLCol58JJyfnuSEvH4N...,RGHDvmXwj8cETX3k68dVVukX9cnPNMYn6VjPbcvSKKQOxG...,0,963900,80.105755,13.641498,47.415849,Interactive,2,2
1,0,gVb4X4iS13nJrM0KZsy7SrHzWAHix0CEPlK7/deV5vkwjt...,14.281488,20.028324,17.250655,+CR55PMlrYL+HxLgi5QmGCKQRMKg1fgaMTJgqZtubpP9UH...,yo3jjkr1k/IzLATyM/i+Dg+xXPs3hYSB8y5DH6fXcoFaJg...,0,2591400,98.993408,20.375766,47.506907,Interactive,2,4
2,0,f8BtQHczrXFjnVxWl8Hqm1kH9UD/8nCvtXCLiFvVRvamqa...,1.655368,23.138685,8.533818,1WfZjuwNwiIBI7l8YNvl9aumxYJ4k6w77mp9HAXnlMZ7gg...,K8lAQjGTDJ2gvxuTHVAgUCBO2avCPOjvACbJDpl+XGEeuX...,0,2591400,98.072864,26.283928,96.998453,Delay-insensitive,4,32
3,0,8xjtVrJRJAyArNlbRgCftoNQOZiWl2eRP6uQavL9+6IULT...,47.501061,52.940579,50.045584,0XnZZ8sMN5HY+Yg+0dykYB5oenlgsrCpzpgFSvn/MX42Ze...,7aCQS6fPUw9rwCPiqvghk/WCEbMV3KgNJjA+sssdfY5Ybl...,0,45000,77.282467,50.968338,74.109584,Unknown,2,4
4,0,zTE3f0H2n43tW+PA3OdonjUTWWxeyzF7xJk9QH9s/487J/...,1.724155,12.889580,4.833578,Z///2IogKMJ9tn3wwZPIb12Y6nVkp30sPuWMFu8KxU+kk8...,2nZ0sO0KcCheoYMnymlrAIqT6NF3ySguScB/YhK7BaXmox...,0,2591400,80.334473,3.378490,14.051767,Delay-insensitive,4,32