In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

usage_path = "/content/drive/MyDrive/diploma_vm_lifecycle/instance_usage_sample_parsed.csv"
events_path = "/content/drive/MyDrive/diploma_vm_lifecycle/instance_events_sample_parsed.csv"

usage = pd.read_csv(usage_path)
events = pd.read_csv(events_path)

In [4]:
usage.head()

,start_time,end_time,collection_id,instance_index,machine_id,average_cpu,average_memory,maximum_cpu,maximum_memory,assigned_memory,page_cache_memory,sample_rate
0,1838400000000,1838700000000,330587238433,111,23624491139,0.008392,0.009476,0.047913,0.019379,0,0.003220,0.996667
1,1839000000000,1839300000000,330587238433,111,23624491139,0.027100,0.027618,0.073608,0.027954,0,0.001808,1.000000
2,942000000000,942300000000,330587238433,111,23624491139,0.024933,0.012466,0.117676,0.019287,0,0.002392,1.000000
3,941700000000,942000000000,330587238433,111,23624491139,0.019135,0.010956,0.120972,0.019318,0,0.001934,1.000000
4,1837800000000,1838100000000,330587238433,111,23624491139,0.001163,0.000959,0.011063,0.001957,0,0.000813,1.000000

In [5]:
events.head()

,time,type,collection_id,instance_index,machine_id,priority,resource_request_cpus,resource_request_memory,alloc_collection_id,alloc_instance_index
0,1992813863543,8,394850707867,249,9.209705e+10,114,0.028625,0.011353,0,-1.0
1,1977541446075,8,394454896092,964,9.386847e+08,114,0.032654,0.010529,0,-1.0
2,278807906571,8,199454074822,13,2.449579e+09,500,0.095581,0.010330,199454074775,NaN
3,483206414250,8,199454074822,12,1.028948e+11,500,0.081421,0.010330,199454074775,NaN
4,2118811402660,8,199454074822,12,8.248194e+10,500,0.111450,0.010300,199454074775,NaN

In [6]:
print(usage.shape, events.shape)

(10000, 12) (10000, 10)

In [7]:
usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   start_time         10000 non-null  int64
 1   end_time           10000 non-null  int64
 2   collection_id      10000 non-null  int64
 3   instance_index     10000 non-null  int64
 4   machine_id         10000 non-null  int64
 5   average_cpu        10000 non-null  float64
 6   average_memory     10000 non-null  float64
 7   maximum_cpu        10000 non-null  float64
 8   maximum_memory     10000 non-null  float64
 9   assigned_memory    10000 non-null  int64
 10  page_cache_memory  10000 non-null  float64
 11  sample_rate        10000 non-null  float64
dtypes: float64(6), int64(6)
memory usage: 937.6 KB

In [8]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   time                     10000 non-null  int64
 1   type                     10000 non-null  int64
 2   collection_id            10000 non-null  int64
 3   instance_index           10000 non-null  int64
 4   machine_id               5270 non-null   float64
 5   priority                 10000 non-null  int64
 6   resource_request_cpus    10000 non-null  float64
 7   resource_request_memory  10000 non-null  float64
 8   alloc_collection_id      10000 non-null  int64
 9   alloc_instance_index     9769 non-null   float64
dtypes: float64(4), int64(6)
memory usage: 781.4 KB

In [16]:
usage_info = pd.DataFrame({
    "table": "instance_usage",
    "column": usage.columns,
    "dtype": usage.dtypes.astype(str).values,
    "non_null_count": usage.notnull().sum().values
})

In [15]:
events_info = pd.DataFrame({
    "table": "instance_events",
    "column": events.columns,
    "dtype": events.dtypes.astype(str).values,
    "non_null_count": events.notnull().sum().values
})

In [17]:
data_dictionary = pd.concat([usage_info, events_info], ignore_index=True)
data_dictionary

              table                   column    dtype  non_null_count
0    instance_usage               start_time    int64           10000
1    instance_usage                 end_time    int64           10000
2    instance_usage            collection_id    int64           10000
3    instance_usage           instance_index    int64           10000
4    instance_usage               machine_id    int64           10000
5    instance_usage              average_cpu  float64           10000
6    instance_usage           average_memory  float64           10000
7    instance_usage              maximum_cpu  float64           10000
8    instance_usage           maximum_memory  float64           10000
9    instance_usage          assigned_memory    int64           10000
10   instance_usage        page_cache_memory  float64           10000
11   instance_usage              sample_rate  float64           10000
12  instance_events                     time    int64           10000
13  instance_events                     type    int64           10000
14  instance_events            collection_id    int64           10000
15  instance_events           instance_index    int64           10000
16  instance_events               machine_id  float64            5270
17  instance_events                 priority    int64           10000
18  instance_events    resource_request_cpus  float64           10000
19  instance_events  resource_request_memory  float64           10000
20  instance_events      alloc_collection_id    int64           10000
21  instance_events     alloc_instance_index  float64            9769